# Generated by Django 3.2.5 on 2021-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_created=True)),
                ('player_a_discord_id', models.IntegerField()),
                ('player_a_display_name', models.CharField(max_length=255)),
                ('player_b_discord_id', models.IntegerField()),
                ('player_b_display_name', models.CharField(max_length=255)),
                ('items', models.CharField(max_length=500)),
                ('transaction_completed', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=501, null=True)),
                ('temp', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
