# Generated by Django 3.2.5 on 2021-07-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20210702_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_start', models.DateTimeField(auto_created=True)),
                ('action_competed', models.DateTimeField(blank=True, null=True)),
                ('interrupted', models.BooleanField(blank=True, null=True)),
                ('actor_discord_id', models.BigIntegerField()),
                ('actor_display_name', models.CharField(max_length=255)),
                ('action_type', models.SmallIntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('mind_cost', models.SmallIntegerField()),
                ('time_cost', models.IntegerField()),
                ('resolve_cost', models.SmallIntegerField()),
                ('materials', models.TextField(max_length=500)),
                ('commentary', models.TextField(max_length=500)),
            ],
        ),
    ]
