# Generated by Django 3.2.5 on 2021-07-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_actionrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionrecord',
            old_name='action_competed',
            new_name='action_completed',
        ),
    ]
