# Generated by Django 3.2.5 on 2021-07-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_rename_action_competed_actionrecord_action_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrecord',
            name='action_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='commentary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='materials',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='mind_cost',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='resolve_cost',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='time_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
