# Generated by Django 3.2.5 on 2021-07-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20210705_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecord',
            name='items',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='action_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'farm'), (2, 'build'), (3, 'upgrade'), (4, 'cook'), (5, 'forage'), (6, 'hunt'), (7, 'salvage'), (8, 'use'), (9, 'smoke'), (10, 'do'), (11, 'trailblaze'), (12, 'spend')], null=True),
        ),
    ]
