# Generated by Django 3.2.5 on 2021-07-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20210705_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrecord',
            name='items',
            field=models.CharField(max_length=255),
        ),
    ]
