# Generated by Django 3.2.5 on 2021-07-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_actionrecord_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecord',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
