# Generated by Django 3.2.5 on 2021-07-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_actionrecord_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecord',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='action_start',
            field=models.DateTimeField(auto_created=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='action_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'brew'), (2, 'build'), (3, 'cook'), (4, 'consume'), (5, 'do'), (6, 'farm'), (7, 'forage'), (8, 'hunt'), (9, 'inject'), (10, 'research'), (11, 'salvage'), (12, 'smoke'), (13, 'spend'), (14, 'trailblaze'), (15, 'upgrade'), (16, 'use')], null=True),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='actor_display_name',
            field=models.CharField(max_length=255, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='tradetransaction',
            name='player_a_display_name',
            field=models.CharField(max_length=255, verbose_name='trader'),
        ),
        migrations.AlterField(
            model_name='tradetransaction',
            name='player_b_display_name',
            field=models.CharField(max_length=255, verbose_name='recipient'),
        ),
        migrations.AlterModelTable(
            name='actionrecord',
            table='logistics_actionrecord',
        ),
        migrations.AlterModelTable(
            name='tradetransaction',
            table='logistics_tradetransaction',
        ),
    ]
