# Generated by Django 3.2.5 on 2021-07-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_auto_20210707_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecord',
            name='flag_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='flag_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
