version: '3.7'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
#  db:
#    << : *restart_policy
#    container_name: dystopic_datastore
#    image: postgres:13.0
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - ${POSTGRES_HOST_PORT}:5432
#    volumes:
#      - dystopic_volume:/var/lib/postgres/data
  web:
    << : *restart_policy
    container_name: dr_logistics_web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - ${WEB_FRONT_OPEN_PORT}:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
#    depends_on:
#      - db
  bot:
    << : *restart_policy
    container_name: dr_logistics_bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u ../dr_logistics/src/LogisticsBot.py
    env_file:
      - .env
#    depends_on:
#      - db

volumes:
  dystopic_volume:
    external: true
    name: dystopic_volume